steps:
 - name: build
    image: maven
    volumes:
      - name: cache # The Volume's name
        path: /root/.m2 # The path in the container
    commands:
      #- mvn help:effective-settings # check maven
      - mvn clean package -DskipTests
volumes:
  - name: cache # The name use in this pipeline,
    host:
      path: /var/lib/cache # The path be used in the host.
